# Generated by Django 5.0.4 on 2024-05-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='username',
            new_name='user',
        ),
    ]
