# Generated by Django 5.0.4 on 2024-05-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0007_book_confirmed_alter_book_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='active',
            new_name='last',
        ),
    ]
