# Generated by Django 5.0.4 on 2024-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0008_rename_active_book_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
